### ISSUE TITLE
Errors running run_webcam.py

### ISSUE THREAD

**Issue by Adilrn** [gsethi2409/tf-pose-estimation#1]
I am experiencing difficulties running the run_webcam.py. This is the error I am getting, how could I resolve the issue?
Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "...\myWorkspace\tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "...\myWorkspace\tf-pose-estimation\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "...\myWorkspace\tf-pose-estimation\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "...\myWorkspace\tf-pose-estimation\tf_pose\estimator.py", line 14, in <module>
    from tensorflow.python.compiler.tensorrt import trt_convert as trt
ImportError: cannot import name 'trt_convert' from 'tensorflow.python.compiler.tensorrt'

**Comment by mohit9949** [comment]
> I am experiencing difficulties running the run_webcam.py. This is the error I am getting, how could I resolve the issue?
> Traceback (most recent call last):
> File "run_webcam.py", line 8, in
> from tf_pose.estimator import TfPoseEstimator
> File "...\myWorkspace\tf-pose-estimation\tf_pose__init__.py", line 5, in
> from tf_pose.runner import infer, Estimator, get_estimator
> File "...\myWorkspace\tf-pose-estimation\tf_pose\runner.py", line 8, in
> from tf_pose import eval
> File "...\myWorkspace\tf-pose-estimation\tf_pose\eval.py", line 13, in
> from tf_pose.estimator import TfPoseEstimator
> File "...\myWorkspace\tf-pose-estimation\tf_pose\estimator.py", line 14, in
> from tensorflow.python.compiler.tensorrt import trt_convert as trt
> ImportError: cannot import name 'trt_convert' from 'tensorflow.python.compiler.tensorrt'

Just for now comment out "from tensorflow.python.compiler.tensorrt import trt_convert as trt" in the estimator.py file and run the script.

**Comment by Adilrn** [comment]
Thank you!
