### ISSUE TITLE
error while running run.py

### ISSUE THREAD

**Issue by mithelan** [gsethi2409/tf-pose-estimation#12]
I'm facing an error while i run
`!python run.py --model=mobilenet_thin --resize=432x368 --image=./images/p1.jpg`

error is
```
Traceback (most recent call last):
  File "run.py", line 39, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/content/tf-pose-estimation/tf_pose/estimator.py", line 337, in __init__
    self.tensor_image = self.graph.get_tensor_by_name('TfPoseEstimator/image:0')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3902, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3726, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3768, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'TfPoseEstimator/image:0' refers to a Tensor which does not exist. The operation, 'TfPoseEstimator/image', does not exist in the graph."
```

**Comment by Cooniecoon** [comment]
hi. I'm in same problem with the error.
if you solved this error, can I ask how did you solve?

**Comment by mithelan** [comment]
@Cooniecoon 
In estimatory.py under the line that imports tensorflow add the following line
 tf.compat.v1.disable_eager_execution()

this sort out my issue.

**Comment by Cooniecoon** [comment]
Thanks for your answer! i'll try it :)

**Comment by gaiadobc** [comment]
If this does not work, add the line 'tf.compat.v1.disable_eager_execution()' directly in the execution cell.

**Comment by zianafique** [comment]
I am facing the same issue and tried all the solutions mentioned above but still it give me same error. Any one solved it?
    

> raise KeyError("The name %s refers to a Tensor which does not "
> KeyError: "The name 'images:0' refers to a Tensor which does not exist. The operation, 'images', does not exist in the graph."
> 

>

**Comment by pa126** [comment]
> @Cooniecoon In estimatory.py under the line that imports tensorflow add the following line tf.compat.v1.disable_eager_execution()
> 
> this sort out my issue.

I could solve this problem based on your advice. 

Regards!

**Comment by yanghualv7** [comment]
> @Cooniecoon In estimatory.py under the line that imports tensorflow add the following line tf.compat.v1.disable_eager_execution()
> 
> this sort out my issue.

Thank you very much. Your method has solved my problem!

**Comment by sahu2003** [comment]
> @Cooniecoon In estimatory.py under the line that imports tensorflow add the following line tf.compat.v1.disable_eager_execution()
> 
> this sort out my issue.

Thank you!!
