### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'`

### ISSUE THREAD

**Issue by KristianDukov** [gsethi2409/tf-pose-estimation#2]
When running the `train.py` I get the following error:

`[2020-05-31 12:31:35,782] [train] [INFO] define model+
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    input_node = tf.placeholder(tf.float32, shape=(args.batchsize, args.input_height, args.input_width, 3), name='image')
AttributeError: module 'tensorflow' has no attribute 'placeholder'`

Using Conda and TF 2.0
Please help

**Comment by ravising-h** [comment]
Can you tell me how you removed this error?
